/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boboyuk;

import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class login_boboyuk extends javax.swing.JFrame {

    /**
     * Creates new form login_boboyuk
     */
    public login_boboyuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bg1 = new javax.swing.JLabel();
        username_icon = new javax.swing.JLabel();
        pass_icon = new javax.swing.JLabel();
        hero1 = new javax.swing.JLabel();
        hero2 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        t_pass = new javax.swing.JTextField();
        forget_pass = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_toregister = new javax.swing.JButton();
        ig_icon = new javax.swing.JLabel();
        lbl_follow1 = new javax.swing.JLabel();
        ig_icon1 = new javax.swing.JLabel();
        ig_icon2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-steve-1509534_1.jpg"))); // NOI18N
        bg1.setText("jLabel1");
        jPanel1.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 220, 363));

        username_icon.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        username_icon.setForeground(new java.awt.Color(27, 137, 171));
        username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_1077063.png"))); // NOI18N
        jPanel1.add(username_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 30, 50));

        pass_icon.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        pass_icon.setForeground(new java.awt.Color(27, 137, 171));
        pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock_15921449.png"))); // NOI18N
        jPanel1.add(pass_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 30, 50));

        hero1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        hero1.setForeground(new java.awt.Color(27, 137, 171));
        hero1.setText("Hello,");
        jPanel1.add(hero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 41, 57, -1));

        hero2.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        hero2.setForeground(new java.awt.Color(19, 91, 141));
        hero2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hero2.setText("WELCOME!");
        jPanel1.add(hero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 68, -1, -1));

        t_username.setText("Username");
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 123, 200, 42));

        t_pass.setText("Password");
        t_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passFocusLost(evt);
            }
        });
        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });
        jPanel1.add(t_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 184, 200, 42));

        forget_pass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        forget_pass.setText("Forget Password?");
        jPanel1.add(forget_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 232, -1, -1));

        btn_login.setBackground(new java.awt.Color(27, 137, 171));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 260, 95, -1));

        btn_toregister.setForeground(new java.awt.Color(27, 137, 171));
        btn_toregister.setText("REGISTER");
        btn_toregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_toregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_toregisterMouseExited(evt);
            }
        });
        jPanel1.add(btn_toregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 260, 95, -1));

        ig_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instagram_5968982.png"))); // NOI18N
        ig_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ig_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ig_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ig_iconMouseExited(evt);
            }
        });
        jPanel1.add(ig_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 318, -1, -1));

        lbl_follow1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_follow1.setText("FOLLOW");
        jPanel1.add(lbl_follow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 318, -1, -1));

        ig_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook_2175193.png"))); // NOI18N
        ig_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ig_icon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ig_icon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ig_icon1MouseExited(evt);
            }
        });
        jPanel1.add(ig_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 318, -1, -1));

        ig_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/github_2111425.png"))); // NOI18N
        ig_icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ig_icon2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ig_icon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ig_icon2MouseExited(evt);
            }
        });
        jPanel1.add(ig_icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 318, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String username=t_username.getText();
        if(username.equals("Username")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passFocusGained
        String pass=t_pass.getText();
        if(pass.equals("Password")){
            t_pass.setText("");
        }
    }//GEN-LAST:event_t_passFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String username=t_username.getText();
        if (username.equals("") || username.equals("Username")){
            t_username.setText("Username");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passFocusLost
        String pass=t_pass.getText();
        if (pass.equals("") || pass.equals("Password")){
            t_pass.setText("Password");
        }
    }//GEN-LAST:event_t_passFocusLost

    private void ig_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_iconMouseClicked
        try{
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/cnpngin._/"));
        } catch (IOException | URISyntaxException ex){
            JOptionPane.showMessageDialog(null, "Gagal Mambuka Link");
        }
    }//GEN-LAST:event_ig_iconMouseClicked

    private void ig_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_iconMouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ig_iconMouseEntered

    private void ig_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_iconMouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_ig_iconMouseExited

    private void ig_icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon1MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ig_icon1MouseEntered

    private void ig_icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon1MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_ig_icon1MouseExited

    private void ig_icon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon2MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ig_icon2MouseEntered

    private void ig_icon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon2MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_ig_icon2MouseExited

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_toregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toregisterMouseEntered
       setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_toregisterMouseEntered

    private void btn_toregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toregisterMouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btn_toregisterMouseExited

    private void ig_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon1MouseClicked
        try{
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/cnpngin._/"));
        } catch (IOException | URISyntaxException ex){
            JOptionPane.showMessageDialog(null, "Gagal Mambuka Link");
        }
    }//GEN-LAST:event_ig_icon1MouseClicked

    private void ig_icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig_icon2MouseClicked
        try{
            Desktop.getDesktop().browse(new URI("https://github.com/ChristianNathanielP"));
        } catch (IOException | URISyntaxException ex){
            JOptionPane.showMessageDialog(null, "Gagal Mambuka Link");
        }
    }//GEN-LAST:event_ig_icon2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_boboyuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_boboyuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_boboyuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_boboyuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_boboyuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_toregister;
    private javax.swing.JLabel forget_pass;
    private javax.swing.JLabel hero1;
    private javax.swing.JLabel hero2;
    private javax.swing.JLabel ig_icon;
    private javax.swing.JLabel ig_icon1;
    private javax.swing.JLabel ig_icon2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_follow1;
    private javax.swing.JLabel pass_icon;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_username;
    private javax.swing.JLabel username_icon;
    // End of variables declaration//GEN-END:variables
}
